"""
Standard disclaimer text.

Appended deterministically by the orchestrator to every final output.
Never generated by an LLM.
"""

DISCLAIMER = (
    "**Disclaimer:** This analysis is generated by an automated AI system and is "
    "provided for informational and educational purposes only. It does not constitute "
    "financial advice, investment advice, or a recommendation to buy, sell, or hold any "
    "security. The system is not a certified financial advisor, analyst, or investment "
    "professional. All data is sourced from publicly available information and may be "
    "incomplete, delayed, or inaccurate. Past performance is not indicative of future "
    "results. Always consult a qualified, licensed financial professional before making "
    "any investment decisions."
)
